import { defineNuxtModule, createResolver, addServerHandler, addServerPlugin, addTypeTemplate, addImports } from '@nuxt/kit'
import { defu } from 'defu'

export interface UnleashProxyConfig {
  url: string
  clientKey: string
  appName: string
  refreshInterval?: number
  environment?: string
}

export type ModuleOptions = UnleashProxyConfig & { customApiPath: string }

export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: 'approck-nuxt-unleash',
    configKey: 'unleash',
  },
  defaults: {
    customApiPath: 'unleash',
  },
  setup(options, nuxt) {
    const { resolve } = createResolver(import.meta.url)

    nuxt.options.runtimeConfig.unleash ||= { ...options }
    nuxt.options.runtimeConfig.public.unleash ||= { customApiPath: 'unleash' }

    nuxt.options.runtimeConfig.unleash = defu(nuxt.options.runtimeConfig.unleash, {
      ...options,
    }) as ModuleOptions

    nuxt.options.runtimeConfig.public.unleash.customApiPath = nuxt.options.runtimeConfig.unleash.customApiPath

    addServerPlugin(resolve('./runtime/server/plugin'))

    // addImportsDir(resolve('./runtime/composables'))

    addImports([
      {
        name: 'useUnleash',
        from: resolve(`./runtime/composables`),
      },
    ])

    nuxt.hook('nitro:config', (nitroConfig) => {
      nitroConfig.alias = nitroConfig.alias || {}

      // Inline module runtime in Nitro bundle
      nitroConfig.externals = defu(
        typeof nitroConfig.externals === 'object' ? nitroConfig.externals : {},
        {
          inline: [resolve('./runtime')],
        },
      )
      nitroConfig.alias['#unleash'] = resolve('./runtime/server/services')
    })
    addTypeTemplate({
      filename: 'types/nuxt-unleash.d.ts',
      getContents: () =>
        [
          '// AUTO-GENERATED BY approck-nuxt-unleash',
          'declare module \'#unleash\' {',
          `  const { unleashClient }: typeof import('${resolve('./runtime/server/services')}')`,
          '}',
          '',
        ].join('\n'),
    })

    addServerHandler({
      route: `/api/${nuxt.options.runtimeConfig.public.customApiPath}/features`,
      handler: resolve('./runtime/server/api/unleash/features.post'),
    })
  },
})
